[package]
name = "chandeliers"
version = "0.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chandeliers-lus = { path = "chandeliers-lus", version = "0.3.1" }
chandeliers-sem = { path = "chandeliers-sem", version = "0.3.1" }
chandeliers-std = { path = "chandeliers-std", version = "0.3.1" }

